worker_processes auto;

error_log logs/error.log warn;
pid       logs/nginx.pid;

env REDIS_HOST;
env REDIS_PORT;
env REDIS_PASSWORD;

events {
    use epoll;
    worker_connections 1024;
    multi_accept on;
}

http {
    include      mime.types;
    default_type application/octet-stream;

    access_log logs/access.log;

    client_body_temp_path temp/client-body;
    proxy_temp_path       temp/proxy;
    fastcgi_temp_path     temp/fastcgi;
    uwsgi_temp_path       temp/uwsgi;
    scgi_temp_path        temp/scgi;

    sendfile       on;
    keepalive_timeout 65;

    lua_package_path  "$prefix/app/?.lua;$prefix/nginx/lua_packages/?.lua;/usr/share/lua/5.1/?.lua;;";
    lua_package_cpath "$prefix/nginx/lua_packages/?.so;;";

    init_by_lua_block {
        require("resty.core")
        require("init")
    }

    include conf.d/*.conf;
}
